### ISSUE TITLE
db issue

### ISSUE THREAD

**Issue by rosshkaa** [Kariel-Myrr/Walk_City#9]

**Comment by AlexanderLazutchik** [comment]
После тестирования лекционного проекта я понял, что мой sql даёт автоматически id начиная с 1, не с 0, что логичнее, хотя в лекции на странице 2 у Вас id начинаются с 0. Теперь я понял, что нужно исправить, но к сожвлению метод update не обновляет несуществующие строки в таблице, что усложнит мне жизнь, так как я буду постоянно проверять существует ли данная строка, так как постоянно очищать таблицу и снова заполнять не выриант. Видимо на этом конфликт исчерпан, хотелось бы получить совет на счет выше указанной проблемы.

**Comment by rosshkaa** [comment]
Проверка существования записи при update - вполне нормальная практика. В качестве альтернативы Kotlin-коду можно оформить процедуру на SQL: https://stackoverflow.com/questions/3634984/insert-if-not-exists-else-update
